// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using mymvc.Data;

#nullable disable

namespace mymvc.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20221017153835_dane1")]
    partial class dane1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("mymvc.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Firstname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "Antoni",
                            Lastname = "Małecki"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "Antoni",
                            Lastname = "Małecki"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "Monika",
                            Lastname = "Gruszka"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "Renata",
                            Lastname = "Malina"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
